#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
#!/bin/bash

# To update the branch shipped in this quickstart, bump this variable:

upstream_branch="stoa29"
repo="https://git.uspdigital.usp.br/6655440/moodle/repository/archive.tar.gz?ref="${upstream_branch}

# Download and install Moodle

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${upstream_branch}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

# If Moodle is already installed in the current gear,
# delete & previous code to build :-)

[ -d "${current_version_dir}" ] && rm -rf ${current_version_dir}
[ -d "${install_dir}" ] && rm -rf ${install_dir}
mkdir -p ${install_dir}

pushd ${install_dir} >/dev/null

# Download & unpack Moodle 

curl -o moodle-${upstream_branch}.tgz -kLs ${repo}
tar --strip-components=1 -xzf moodle-${upstream_branch}.tgz
rm -rf moodle-${upstream_branch}.tgz
echo $upstream_branch > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_branch

# Download & unpack other Packages

popd >/dev/null
